### PR TITLE
Improve Nix usage instructions. Regenerate Cargo.nix.

### PR DESCRIPTION
**Pull request by nothingnesses**
Since Cargo.lock was changed with commit 6975488b0c253ee598981aaaf3260d7d9cfab74c. (Note: when Cargo.lock changes, `crate2nix generate` needs to be ran to update Cargo.nix)

### CODE REVIEW

**Comment by quleuber** [comment]
could we write a pre-publish script or something like that? i will never remember to run that command in particular  :P

**Comment by nothingnesses** [comment]
@quleuber Not sure, but yeah, it's probably possible to do that. I'll have to look into it more as I don't know how it'd be done for sure.

**Comment by quleuber** [comment]
i mean, not something automatic (could be optional) but just a script that we would run when we want to push that runs tests, rebuilds the Nix file etc

**Comment by nothingnesses** [comment]
@quleuber Ah right. Not sure how useful that would be if we'd still need to manually run it though? Like we might still forget to run it after making a change that changes Cargo.lock. It'd have to be another thing we'd have to keep in mind which I personally wouldn't want to have to remember.

**Comment by balsoft** [comment]
> Although maybe that's been fixed, I haven't checked recently.

It has been fixed by https://github.com/NixOS/nix/pull/5494

**Comment by nothingnesses** [comment]
@balsoft Ah thanks for making me aware, I'll try using `generatedCargoNix` again to see if it works. I'm admittedly somewhat new to nix, so I'd really appreciate it if you could look over my implementation of the flake as well (especially the commented part that's supposed to use `generatedCargoNix`) and let me know if there's any errors/bad practices.

**Comment by nothingnesses** [comment]
@balsoft Ah thanks for making me aware, I'll try using `generatedCargoNix` again to see if it works. I'm admittedly somewhat new to nix, so I'd really appreciate it if you could look over my implementation of the flake as well (especially the commented part that's supposed to use `generatedCargoNix`) and let me know if there's any errors/bad practices.

**Comment by balsoft** [comment]
The code there LGTM. Not sure if it can be improved significantly.

**Comment by nothingnesses** [comment]
@balsoft Ok thanks. The thing is though, I just tried replacing [this part of the code](https://github.com/Kindelia/HVM/blob/94e67e1f4ba44649ddb3f34ec6c5f1c501eff3f3/flake.nix#L85-L92) with [the commented out part](https://github.com/Kindelia/HVM/blob/94e67e1f4ba44649ddb3f34ec6c5f1c501eff3f3/flake.nix#L70-L84) earlier and starting a dev shell, and it resulted in an error: 

```
$ nix develop
warning: Git tree '/home/.shared/repositories/github/Kindelia/LambdaVM-Rust' is dirty
error: store path '/nix/store/ggxm4bm1kx0skc00xvi8cq25bnf4rkg5-hvm-crate2nix' is not allowed to have references
(use '--show-trace' to show detailed location information)
$
```

So I think the code is maybe incorrect? Or maybe some other bug exists? If you have some free time, would you mind trying it out and confirming that this happens to you too?

**Comment by balsoft** [comment]
You need to update your Nix version :)

**Comment by nothingnesses** [comment]
D'oh. Of course. I'm still on Nix 2.4 :man_facepalming: . Thanks!

**Comment by nothingnesses** [comment]
@balsoft I updated to 2.5.1, but now I'm getting a different error:
```
$ nix --version
nix (Nix) 2.5.1
$ \rm flake.lock
$ nix develop
warning: Git tree '/home/.shared/repositories/github/Kindelia/LambdaVM-Rust' is dirty
warning: creating lock file '/home/.shared/repositories/github/Kindelia/LambdaVM-Rust/flake.lock'
warning: Git tree '/home/.shared/repositories/github/Kindelia/LambdaVM-Rust' is dirty
error: cannot yet have refs with flat or nar-hashed data
(use '--show-trace' to show detailed location information)
$
```
If you have the same version, can you confirm?

**Comment by balsoft** [comment]
I'm on 2.6.0pre20220120_0670762, it works just fine with just the changes you described (to check that it doesn't use Cargo.nix, I removed it).

**Comment by balsoft** [comment]
```
$ nix develop
warning: Git tree '/home/balsoft/projects/HVM' is dirty

[balsoft@AMD-Workstation:~/projects/HVM]$
exit
$ nix shell
warning: Git tree '/home/balsoft/projects/HVM' is dirty
$ hvm
High-order Virtual Machine (0.1.4)
==========================

To run a file, interpreted:

  hvm run file.hvm

To compile a file to C:

  hvm c file.hvm

More info: https://github.com/kindelia/hvm
```

**Comment by nothingnesses** [comment]
@balsoft Ah that's great to hear! I guess I'll just wait for Nix 2.6 to release and then enable the commented code that uses `generatedCargoNix` when it does. Anyway, thanks again, I really appreciate the help!

**Pull request merged**
