### PR TITLE
Improve README. Add Matrix bridge link.

### PR DESCRIPTION
**Pull request by nothingnesses**

### CODE REVIEW

**Comment by VictorTaelin** [comment]
SHouldn't we encourage people to join the server?

**Comment by nothingnesses** [comment]
Well the Matrix bridge connects to the Discord server and vice versa, so you can access the messages from either platform if you join either one. The Matrix bridge is essentially just a convenient way for people to access the Discord server since they don't have to have a lot of messaging apps on their device to be able to communicate with people on different platforms (i.e., I just use my Matrix client to communicate with people on Telegram and Discord, so I don't have to visit their separate apps, I just access everything from Element).

**Comment by VictorTaelin** [comment]
Yes but I guess that's kinda against the spirit of Discord communities, no?

**Comment by nothingnesses** [comment]
I'm not sure I understand what you mean, would you care to elaborate?

**Comment by VictorTaelin** [comment]
Discord communities are fun because everyone is able to join, get roles, participate on voice chats, etc. You don't have that if you join on Matrix, right?

**Comment by nothingnesses** [comment]
Ah crap, the Discord link broke. It seems I doubled the parentheses around the link, sorry.

**Pull request merged**
