### PR TITLE
Bunch of changes.

### PR DESCRIPTION
**Pull request by nothingnesses**
- [x] Check and test Rust code.
- [x] Only check Rust formatting instead of applying it.
- [x] CI for Nix build.
- [x] Eliminate CI failures.
- [x] Remove unused dependencies in Cargo.nix.
- [x] Fix flake.
- [x] Improve TL;DR.
- [ ] Check and test C outputs.

### CODE REVIEW

**Comment by VictorTaelin** [comment]
Should we fix these unsuccessful checks before merging?

**Comment by nothingnesses** [comment]
They're just the clippy lints and formatting checks. I think before we fix the formatting failures, it might be a good idea for you to peruse the [rustfmt documentation](https://rust-lang.github.io/rustfmt/), review the actual rustfmt.toml configuration we currently have and make changes to it to your liking so that we can have a consistent "house style" for the whole project that every contributor can agree to stick to.

**Comment by VictorTaelin** [comment]
Okay, I'll do that when I get back to work

**Comment by VictorTaelin** [comment]
Okay, that is huge. I don't really have strong opinions, I agree with whatever the Rust community finds good, other than tabs being 2 spaces.

**Comment by nothingnesses** [comment]
That's fine. The good thing about having a formatter is we can just edit the configuration later on and have it automatically re-format the code later on, so we don't have to stick to one style forever. So in that case, if you're happy with the current config, I can try fixing the causes of the CI failures and update this so that this can finally be merged?

**Comment by nothingnesses** [comment]
@VictorTaelin I've eliminated the CI failures. I re-denied some previously globally allowed lints, making some of them locally allowed instead (i.e., mostly adding the `#[allow(dead_code)]` attribute above a couple of functions) or actually replacing the code that clippy was complaining about (i.e., mostly adding underscores before unused variables). Please feel free to review whenever.

**Comment by nothingnesses** [comment]
> Okay, that is huge. I don't really have strong opinions, I agree with whatever the Rust community finds good, other than tabs being 2 spaces.

Wait, I just re-read your comment and I'm not sure I interpreted it correctly. Just to be clear, are you saying that the tabs *should* be 2 spaces, or *shouldn't* be 2 spaces? If it's the latter, please could you let me know how many spaces it should be, instead of 2?

**Comment by VictorTaelin** [comment]
Can it not touch the hadouken?

**Comment by nothingnesses** [comment]
> Can it not touch the hadouken?

I think we could use `#[rustfmt::skip]` for that. Let me check.

**Pull request merged**
