### PR TITLE
Makes a parallel sum the standard program in case the runtime is compiled by itself

### PR DESCRIPTION
**Pull request by cauefcr**
Saw the issue and decided to fix it.

### CODE REVIEW

**Comment by VictorTaelin** [comment]
Not sure I get it, that means every compilation will jet injected the FIB function, even if unrelated? 

Has `--single-thread` been removed?

**Comment by quleuber** [comment]
> expressions to be replaced like in the comment I quoted

I'll implement this.

**Comment by quleuber** [comment]
I closed the original issue (#53) by other means. Now we just have to decide if we keep a default program on `runtime.c` or not.

**Comment by VictorTaelin** [comment]
Hi, any updates on the state of the review of this PR? Can it be merged?

**Pull request closed without merging**
