### PR TITLE
refactor: apply all clippy lints and cargo format.

### PR DESCRIPTION
**Pull request by zicklag**
Not sure if you guys are ready for this or not, but here it is if it helps!

### CODE REVIEW

**Comment by zicklag** [comment]
I also switched the rust toolchain to nightly in CI, because the crate doesn't compile on stable right now, but it doesn't seem like the CI jobs will run anymore.

**Comment by zicklag** [comment]
Actually, I just realized it'd be really easy to support stable. We'd just have to polyfill the two nightly methods we're using I think.

I could try to add that.

**Comment by VictorTaelin** [comment]
Thank you so much! I really want to accept this commit but there are many things that similar PRs broken before (like some alignments here and there) so I'll need to have a look on everything before I'm able to merge it. I'll be back to coding when I'm done with fundraising work. Great work, thanks

**Comment by zicklag** [comment]
Sounds good!

To ease the review burden, as I know this is a ton of changed code, maybe I should do separate PRs for the automatic application of `cargo fmt` and the clippy lints which were semi-automatic and semi-manual.

Once I get the chance, I'll try to open 3 PRs:

- Cargo format
- Clippy fix
- Polyfill nightly methods so we can compile on stable.

**Pull request closed without merging**
